#!/usr/bin/env python
# -*- coding: latin-1 -*-

import gtk
import os
import sys
import string

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])),".."))
import Process

def ClickAccept(widget):
	Process.ProcessFiles(
		"pdfnup $FILE$ --nup " + str(int(adjHorizontal.get_value())) + "x" + str(int(adjVertical.get_value())), 
		"pdf", # tipo de archivos
		False, # leer directorios?
		False, # procesar directorio como un archivo
		"") # mensaje final
	gtk.main_quit()

def ClickCancel(widget):
	gtk.main_quit()

# PROGRAMA

if Process.verifyCommands("pdfnup%pdfjam")==False:
	sys.exit()

w = gtk.Window(gtk.WINDOW_TOPLEVEL)
w.set_title("Reducir páginas de un PDF")
w.set_border_width(20)

w.connect("destroy", gtk.main_quit) 

# tabla

tableMin = gtk.Table(2, 1, False)
tableMin.set_border_width(10)

tableMin.set_row_spacings(8)
tableMin.set_col_spacings(8)


lVertical = gtk.Label("Páginas vertical:")

tableMin.attach(lVertical, 0, 1, 0, 1)


adjVertical = gtk.Adjustment(1.0, 0.0, 4.0, 1.0, 5.0, 0.0)
spinVertical = gtk.SpinButton(adjVertical, 0, 0)
adjVertical.set_value(1)

tableMin.attach(spinVertical, 1, 2, 0, 1)

lHorizontal = gtk.Label("Paginas horizontal:")

tableMin.attach(lHorizontal, 0, 1, 1, 2)

adjHorizontal = gtk.Adjustment(1.0, 0.0, 4.0, 1.0, 5.0, 0.0)
spinHorizontal = gtk.SpinButton(adjHorizontal, 0, 0)
adjHorizontal.set_value(2)

tableMin.attach(spinHorizontal, 1, 2, 1, 2)


# botones

aligButtons = gtk.Alignment(1.0, 0.0)
boxButtons = gtk.HBox(True, 4)

bAccept = gtk.Button("Aceptar", gtk.STOCK_OK)

bAccept.connect("clicked", ClickAccept)

boxButtons.pack_start(bAccept, False, False, 0)

bCancel = gtk.Button("Cancelar", gtk.STOCK_CANCEL)

bCancel.connect("clicked", ClickCancel)

boxButtons.pack_start(bCancel, False, False, 0)

aligButtons.add(boxButtons)

tableMin.attach(aligButtons, 1, 2, 4, 5)

w.add(tableMin)
w.show_all()
gtk.main()
