#!/usr/bin/env python
# -*- coding: latin-1 -*-

import sys, os

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])),".."))
import Process

if Process.verifyCommands("oggdec%vorbis-tools")==False:
	sys.exit()

Process.ProcessFiles(
	"oggdec $FILE$", # comando a ejecutar
	"ogg", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
