#!/usr/bin/env python
# -*- coding: latin-1 -*-

import sys, os

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])),".."))
import Process

if Process.verifyCommands("lame|oggenc%vorbis-tools")==False:
	sys.exit()

Process.ProcessFiles(
	"lame -h --decode $FILE$ $NAME$.wav", # comando a ejecutar
	"mp3", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final

Process.ProcessFiles(
	"oggenc $NAME$.wav", # comando a ejecutar
	"mp3", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final

Process.ProcessFiles(
	"rm $NAME$.wav", # comando a ejecutar
	"mp3", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
